name: Build project

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.12f1-update-2020-10-08
        testMode:
          - playmode
          - editmode
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          lfs: true
      - uses: actions/cache@v2.1.2
        with:
          path: /Library
          key: Library-
          restore-keys: |
            Library-
      - uses: webbertakken/unity-test-runner@v1.7
        id: tests
        with:
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          customParameters: -enableCodeCoverage -coverageResultsPath /github/workspace/${{ matrix.testMode }}-artifacts/coverage.xml -coverageOptions generateAdditionalMetrics;generateHtmlReport;generateHtmlReportHistory;generateBadgeReport;assemblyFilters:+Assembly-CSharp
      - uses: actions/upload-artifact@v2
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}