name: Test Suite

on: [push]

jobs:
  testRunner:
    name: Test Runner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - testModeFlat: "playmode"
            testModePascal: "PlayMode"
          - testModeFlat: "editmode"
            testModePascal: "EditMode"
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      # Cache
      - name: Cache library files
        uses: actions/cache@v2.1.3
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.7
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: 2019.3.7f1
          testMode: "${{ matrix.testModeFlat }}"
          customParameters: -enableCodeCoverage

      # Output - Unit tests
      - name: Upload unit test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: artifacts

      # Output - Coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: CodeCoverage
          path: CodeCoverage

      # Upload coverage to codecov
      - name: Save coverage report to CodeCov
        uses: codecov/codecov-action@v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          file: ./CodeCoverage/workspace-opencov/${{ matrix.testModePascal }}/TestCoverageResults_0000.xml
          fail_ci_if_error: true
